# Generated by Django 5.1.2 on 2024-12-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='director_name',
        ),
        migrations.CreateModel(
            name='ContentDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.content')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.director')),
            ],
            options={
                'unique_together': {('content', 'director')},
            },
        ),
        migrations.AddField(
            model_name='content',
            name='directors',
            field=models.ManyToManyField(through='DataBase.ContentDirector', to='DataBase.director'),
        ),
    ]
