# Generated by Django 5.1.2 on 2024-12-08 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0002_director_remove_content_director_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentlist',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='contentlist',
            name='list_name',
        ),
        migrations.RemoveField(
            model_name='contentlist',
            name='userprofile',
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='contentlist',
            name='list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='DataBase.list'),
            preserve_default=False,
        ),
    ]
