# Generated by Django 5.1.3 on 2024-12-19 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0003_user_is_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='userprofile',
        ),
        migrations.AddField(
            model_name='notification',
            name='content_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DataBase.content'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProfileNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('read', 'Read'), ('unread', 'Unread')], max_length=10)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.userprofile')),
            ],
        ),
    ]
