# Generated by Django 5.1.2 on 2024-12-08 18:28

import DataBase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0003_remove_contentlist_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=DataBase.models.unique_upload_path),
        ),
    ]
