# Generated by Django 5.1.2 on 2024-12-21 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0004_remove_notification_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='content_id',
            new_name='content',
        ),
        migrations.AddField(
            model_name='userprofilenotifications',
            name='notification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='DataBase.notification'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofilenotifications',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='DataBase.userprofile'),
        ),
    ]
