upstream film-time {
    server web:8000;
}

server {
    listen 80;

    server_name film-time;

    location /static/ {
        alias /app/static/;  # Serve static files from Django's static directory
    }

    location / {
        proxy_pass http://web:8000;  # Forward to Gunicorn
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
