server {
    listen 80;
    server_name film-time;

    root /app/views;
    index homepage.php;

    location /styles/ {
        root /app;
    }
    location / {
        try_files $uri $uri/ /homepage.php?$query_string;
        autoindex on;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index homepage.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # python api stuff
    location /api/ {
        proxy_pass http://web:8000;  # Forward to Gunicorn
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
